### ISSUE TITLE
meeting on Oct 10

### ISSUE THREAD

**Issue by TanyaNikitina** [KatyaAplonova/ReportedDiscourseProject#11]
I propose Oct 10 as the date of this year's 3rd meeting. We could start at 11am and do updates for an hour, then resume after lunch. Please mark the calendars!

**Comment by KatyaAplonova** [comment]
OK!

**Comment by IndianaTones** [comment]
Done

**Comment by IndianaTones** [comment]
* ELAN annotations/questions
* Tier standardization
* Current and wish-list searching
* Groups & Links
* 4th Symposium on West African Languages Panel Update
* File naming conventions

**Comment by rvoll** [comment]
Hi guys! 
I'm sorry but my daughter is sick with fever so I'll have to stay home tomorrow.
Maybe I can join you on skype...

**Comment by rvoll** [comment]
Could you please write a protocoll for the meeting and put it on Github? Skyping may be difficult. Then I'll call one or the other of you later to get a more detailed update, if possible.
