### ISSUE TITLE
RA search - Interview scheduling - 01 October 2019

### ISSUE THREAD

**Issue by Avamuru** [KatyaAplonova/ReportedDiscourseProject#22]
Hello, please let me know your availability for interviews on 1 Oct by filling out this when2meet poll. Thank you. https://www.when2meet.com/?8167899-9BvWP 
You may also see this request on a the group chat in Skype. It's the same link/same request.
Thank you,
Becky

**Comment by Avamuru** [comment]
Thank you all for adding your availability to the when2meet poll. The three interviews are all tentatively scheduled for Tuesday, 1 Oct, in the afternoon. I have sent confirmation emails to each interviewee to hopefully finalize the times with each one. The tentative times are on the Google calendar and listed below.

Othaniel - **2pm**  - all four of us are available - skype name: nlabefi_othaniel
Juan Carlos Rodriguez (Burgos)- **4:30pm** - T, A and B are available - skype name: jcake19
Elias Williams - **5:30pm** - T and B are available - skype name: elias.williams16

**Comment by IndianaTones** [comment]
Apologies, I can also be available at 5:30.
