### ISSUE TITLE
Bashkir corpus

### ISSUE THREAD

**Issue by KatyaAplonova** [KatyaAplonova/ReportedDiscourseProject#26]
During this week I've annotated with Template about 2 hours of Bashkir texts and I have couple of annotation questions, which I'd like to discuss. Notes are in attachments.

Will we have time to discuss it tomorrow, what do you think? It shouldn't take more than 30 minutes.
[011019_ProjectMeeting_KA.docx](https://github.com/KatyaAplonova/ReportedDiscourseProject/files/3670239/011019_ProjectMeeting_KA.docx)

**Comment by TanyaNikitina** [comment]
Sure, let's incorporate it into the agenda.

**Comment by KatyaAplonova** [comment]
I've found [an article about "new quotatives" in English](http://www.lel.ed.ac.uk/~pgc/archive/2002/proc02/buchstaller02.pdf), maybe it would be usefull for our discussion of non-speech verbs, which introduce RD.
