### ISSUE TITLE
Logophoroids

### ISSUE THREAD

**Issue by IndianaTones** [KatyaAplonova/ReportedDiscourseProject#31]
Let's talk about logophorics and logophoric-like pronouns for a [SyWAL2020](http://www.unior.it/ricerca/19760/3/call-for-panels.html) panel submission! 

In particular to my Dogon Ben Tey corpus, logophorics can (and often do) occur outside of the *speech report*, opposing the classic definition: "speech, thoughts, or feelings are reported or reflected in a given linguistic context" (Clements 1975: 141).

**Comment by TanyaNikitina** [comment]
Elena and Lacina may have something to say on logophoric-like uses of 3rd person pronouns (their logophorics are basically emphatic forms of 3rd person pronouns, also used outside reported speech contexts).

**Comment by rvoll** [comment]
I think the same is the case in Tikar - at least for one set of logophoric pronouns..

**Comment by Avamuru** [comment]
Ut-Ma'in does not have dedicated logophoric pronouns, but I do have an emerging pattern (read: I have not yet figured out what is going on, nor do I know how widespread of a phenomenon it may be) of "listener" 3rd person pronouns within reported speech. The pattern is that the reported speaker uses a 1st person pronoun in the reported speech to refer to himself (the reported speaker), but a 3rd person (sg) pronoun (_wa_) to refer to the reported listener. The 3rd person pronoun is translated into English by my consultant as 2nd person, and context is clear that the 3rd person pronoun MUST refer to the reported listener and not any other story participant. 

There is also a noteworthy pattern of using "impersonal" pronoun (_na_) constructions (the only way passive is accomplished in the language), which use a "special" 1pl/3pl/indefinite? pronoun to downplay the agent in a sequence of events. In some cases, the agent is readily apparent. In other cases the _na_ pronoun is non-referential or the agent is not recoverable from context.

Would these phenomena be considered logophoric-like enough for the panel proposal? I'm writing up an abstract regardless, but I'm happy to integrate this into the panel if it would fit.

**Comment by IndianaTones** [comment]
Awesome!  I am also doing a comparative search so if you all have annotated files it would be great to integrate them.

**Comment by rvoll** [comment]
I just sent this to Abbie via email - still gotta adapt to this multiparticipant communication channel - although I find it great!! So once again for all...
At this point, I am not sure whether the song or multimodality panel are gonna happen, so I might wanna end up on your panel, too. I am pasting below a draft for an abstract on Tikar (based mainly on Jackson 1987, so far) which I think should fit. I could do either this or present on the Mundabli self-quotation marker and how it should be interpreted as an instance of logophoricitz in the wider sense. But then, I had thought, that doesn't quite fit the topic, does it?
So here's my Tikar abstract:

[2020-09_SyWal_TikarLogolikePros_version_2019-10-09.docx](https://github.com/KatyaAplonova/ReportedDiscourseProject/files/3706690/2020-09_SyWal_TikarLogolikePros_version_2019-10-09.docx)

**Comment by IndianaTones** [comment]
Uses of "logophorics" outside of discourse reports: 

logophoric and non-logophoric uses emerge outside of the speech reporting domain

**Comment by rvoll** [comment]
Hi guys! 
I've worked on my abstract for the logophorics and logophoric-like pronouns panel. I am uploading it in case you wanna take a look before the meeting tomorrow.

[2020-09_SyWal_TikarLogolikePros_version_2019-10-22_abstract-only.docx](https://github.com/KatyaAplonova/ReportedDiscourseProject/files/3761079/2020-09_SyWal_TikarLogolikePros_version_2019-10-22_abstract-only.docx)

**Comment by Avamuru** [comment]
@IndianaTones 
My abstract. Formatted. Ready to go.

[UnattestedPersonAlignment_LogophoricFunction.docx](https://github.com/KatyaAplonova/ReportedDiscourseProject/files/3793689/UnattestedPersonAlignment_LogophoricFunction.docx)
[UnattestedPersonAlignment_LogophoricFunction.pdf](https://github.com/KatyaAplonova/ReportedDiscourseProject/files/3793690/UnattestedPersonAlignment_LogophoricFunction.pdf)

**Comment by Avamuru** [comment]
Formatted versions of Tikar Abstract. Only formatting edits were related to stylesheet, for consistency.
 
[Tikar logophorics and the typology of multifunctional logophoric pronouns.docx](https://github.com/KatyaAplonova/ReportedDiscourseProject/files/3793854/Tikar.logophorics.and.the.typology.of.multifunctional.logophoric.pronouns.docx)
[Tikar logophorics and the typology of multifunctional logophoric pronouns.pdf](https://github.com/KatyaAplonova/ReportedDiscourseProject/files/3793855/Tikar.logophorics.and.the.typology.of.multifunctional.logophoric.pronouns.pdf)

**Comment by IndianaTones** [comment]
Submitted!
