### ISSUE TITLE
meeting Nov 19

### ISSUE THREAD

**Issue by TanyaNikitina** [KatyaAplonova/ReportedDiscourseProject#33]
It looks like Nov 19 after lunch might be a good time for a meeting. Please mark the calendar. We will have another meeting on either Nov 5 or Nov 6, I hope to confirm the date next week.

**Comment by Avamuru** [comment]
I added Nov 19 Project meeting to the google calendar for 2-4pm. I added TENTATIVE meetings on Nov 5 and 6.

**Comment by rvoll** [comment]
Do you mind if we have the meeting from 1 to 3 rather than 2 to 4?
