### ISSUE TITLE
Email signatures

### ISSUE THREAD

**Issue by Avamuru** [KatyaAplonova/ReportedDiscourseProject#35]
Is there a recommended email signature to use for our project or our various roles/positions? I am curious what you put at the end of your emails. A logo? Any input is welcome. Thanks.

**Comment by IndianaTones** [comment]
I use this:



 Abbie HANTGAN-SONKO
 
CNRS LLACAN Paris-Villejuif l Post-doctorante
projet Européen - Speech Reporting
7, rue Guy Môquet 94800 Villejuif
01 49 58 33 96
https://sites.google.com/view/speechreporting/people
http://llacan.vjf.cnrs.fr/p_hantgan.php
