### ISSUE TITLE
Timofey's visit

### ISSUE THREAD

**Issue by TanyaNikitina** [KatyaAplonova/ReportedDiscourseProject#37]
I am trying to organize Timofey's visit for Nov 5-7. Let me know if you have any objections and please be prepared to spend time with him on those days! Let us finalize the dates of Nov 5-6 as the dates of project meetings and Nov 7 as an additional day for those involved with Timofey more closely (Katya, Abbie, Lacina). 
Abbie, could you please check with Christian if he is around on at least some of those days?

**Comment by KatyaAplonova** [comment]
Cool! Dates are good for me.

Maybe, we should create a list of topics to discuss with Timofey?

**Comment by TanyaNikitina** [comment]
Good idea! Feel free to start the list, and to brainstorm at your next meeting!

**Comment by IndianaTones** [comment]
Ok, Christian will be available on the 5th only...

**Comment by TanyaNikitina** [comment]
The current plan is for him to arrive on Nov 5 after lunch and leave on Nov 6 in the afternoon (perhaps around 17h I hope).

**Comment by TanyaNikitina** [comment]
All is set for Timofey's visit on Nov 5-6. Rebecca, could you please take care of his authorization to access the campus? Abbie and Katya, he may need your contact info in case he has trouble finding us. Also, could you please prepare an agenda for meeting with him and take care of the projector and other technical issues?

**Comment by rvoll** [comment]
I'll take care of the authorisation!

**Comment by KatyaAplonova** [comment]
My phone number is: 0766119605

There are some topics to discuss:
- morpheme level segmentation in the corpus
example: how to find a noun without some marker (now, it is impossible, because negative query is available only on the word/lemma level)
- corpus support
example: who will have rights to upload new texts to the corpus

What else?..

**Comment by rvoll** [comment]
Hi! I saw that meetings are announced on the 5th and 6th in the morning. From what you said in the earlier comment ("The current plan is for him to arrive on Nov 5 after lunch and leave on Nov 6 in the afternoon (perhaps around 17h I hope)."), wouldn't it make more sense to have the first meeting in the afternoon of the 5th? Do I understand right that we have a two day meeting? I am just wondering whether the times as announced in the calendar are precise or whether we only start in the afternoon on the 5th - which would actually be more practical for me.

**Comment by TanyaNikitina** [comment]
We will start after lunch on Nov 5, because Timofey only arrives at 11:30 at CDG, and I have a meeting at LACITO at 11am. On Nov 6, we will try to start at 9am.
Could someone get in touch with Timofey, explain to him how to access the campus and find us, and also give him Katya's phone number in case he gets lost?

**Comment by rvoll** [comment]
We're in touch with him already. I'm taking care of it!

**Comment by IndianaTones** [comment]
[Tsakorpus Platform](https://bitbucket.org/tsakorpus/tsakorpus/src/master/docs/pipeline.md)

**Comment by rvoll** [comment]
Should we move this link to a permanent place in Github? I guess this issue will get deleted at some point of time...

**Comment by IndianaTones** [comment]
Hi all -

I made a new folder in Code for all things Tsakorpus (Timofey's corpus platform).

Feel free to add notes and such there.

The conversion process is also now up and running :)
