### ISSUE TITLE
ELAN question/answer/discussion session on 25th

### ISSUE THREAD

**Issue by rvoll** [KatyaAplonova/ReportedDiscourseProject#38]
I would like to initiate an ELAN question/answer/discussion session on the 25th after lunch, i.e. at 1pm (end open). I think it would be good to have a separate session for this because we may not have enough time to solve all problems during teh general meeting on the 24th. 

Could everyone who will be at the meeting on the 24th please reply and say whether you are interested and if the timing works for you?
Thanks!

**Comment by Avamuru** [comment]
I am available on the 25th in the afternoon and will plan to be there. You do mean Friday, the 25th? The day after our general meeting?
-Becky

**Comment by KatyaAplonova** [comment]
I leave the 23th to Bashkiriya, so I won’t be there.

**Comment by elenap96** [comment]
I also will be absent.
Elena Perekhvalskaya, PhD

**Comment by rvoll** [comment]
Shame you won't be there Katya and Elena! But I guess we will have more of those and maybe we come up with a plan on how to do it online...
Abbie, will you be there? Could you ask Lacina? I have sent him an email but he should actually join the GitHub group!

**Comment by IndianaTones** [comment]
I shall be there and will talk to Lacina

**Comment by rvoll** [comment]
Great, Abbie!Thanks!I've already talked to Lacina. He will be there, too. But maybe you better talk to him anyway. I'm not sure whether he is aware of the general meeting on Thursday as he is not on  Github...
See you on Thursday!
Rebecca
    Am Montag, 21. Oktober 2019, 11:33:45 MESZ hat Abbie Hantgan <notifications@github.com> Folgendes geschrieben:  
 
 
I shall be there and will talk to Lacina

**Comment by rvoll** [comment]
Hi Timofey!
Thanks for the details.
This is just to make sure you reach campus and get inside:
This is where the Villejuif cnrs campus is:
Paris-Charles-de-Gaulle-flygplatsen to Cnrs Délégation Paris-Villejuif

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Paris-Charles-de-Gaulle-flygplatsen to Cnrs Délégation Paris-Villejuif

Hitta lokala företag, titta på kartor och hämta vägbeskrivningar i Google Maps.
 |

 |

 |


7 Rue Guy Môquet

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
7 Rue Guy Môquet

7 Rue Guy Môquet, 94800 Villejuif, France
 |

 |

 |


Once you're at the gate, ring the bell, tell the guard your name and that you're a visitor and your name's on their list. I can't recall right now what the building is called - each building is labelled with a letter. Anyway, just ask the guard! Or call Katya or me to pick you up at the gate. In fact, you can't really get into the buildiung unless you have a card...except via the metal staircase through the kitchen door ´, which is usually propped open.

Just in case you have any problem getting there, or in case they don't let you in - which has happened before but I don't think it will - you can contact Katya - this is her number: 0033-766119605 - or me: 0049-15163221386.Have a good trip!
Rebecca






    Am Montag, 28. Oktober 2019, 12:53:48 MEZ hat Тимофей Архангельский <timarkh@gmail.com> Folgendes geschrieben:  
 
 Hi Rebecca and Abbie,
Thanks! My name should actually be transliterated as "Timofey Arkhangelskiy" (at least that's what I normally use). My number is +491747125521, and the dates are correct.
Best,Timofey
пт, 25 окт. 2019 г. в 17:32, rebecca voll <rebecca_voll@yahoo.de>:

 Thanks Abbie!
Hi Timofey!
I'm also part of the Discourse reporting project...Could you please send me your telephone number?
I need it to issue an application for access on campus for you on the 5th-6th of november. Let me know if you want to stay longer, then I will apply for more days.The system requires that we apply before a visitor comes, otherwise they are not able to get onto campus, so it is important that we cover the whole time you will actually be at the Llacan.
Thanks for sending me your number and the exact dates!
Best wishes,
Rebecca


    Am Freitag, 25. Oktober 2019, 16:30:48 MESZ hat Abbie Hantgan <ahantgan@gmail.com> Folgendes geschrieben:  
 
 Hi Rebecca,
This is to introduce you to Timofey with his contact details so you can make sure he has access to campus from November 5-6. 

Hi Timofey,
Please make sure that I transliterated your name correctly:

Тимофей Архангельский (Timofey Arhangelski)timarkh@gmail.com
Looking forward to seeing you soon,

Abbie

**Comment by rvoll** [comment]
Okay, thanks a lot! Sounds reasonably complicated, let's see if I manage to
get in. :) What about the time: can I just show up at any moment, or should
I warn you some time in advance, e.g. when I get on the Paris-bound train?

пт, 1 нояб. 2019 г. в 23:39, rebecca voll <rebecca_voll@yahoo.de>:

> Hi Timofey!
>
> Thanks for the details.
> This is just to make sure you reach campus and get inside:
>
> This is where the Villejuif cnrs campus is:
>
> Paris-Charles-de-Gaulle-flygplatsen to Cnrs Délégation Paris-Villejuif
> <https://www.google.com/maps/dir/Paris-Charles+De+Gaulle+(CDG),+Roissy-en-France,+Frankreich/llacan+villejuif+adresse/@48.9024495,2.3070045,11z/data=!3m1!4b1!4m14!4m13!1m5!1m1!1s0x47e63e038e4ccf5b:0x42be0982f5ba62c!2m2!1d2.5479245!2d49.0096906!1m5!1m1!1s0x47e671608cba6615:0x952302ded2a0d0ba!2m2!1d2.358777!2d48.796767!3e3>
>
> Paris-Charles-de-Gaulle-flygplatsen to Cnrs Délégation Paris-Villejuif
>
> Hitta lokala företag, titta på kartor och hämta vägbeskrivningar i Google
> Maps.
>
> <https://www.google.com/maps/dir/Paris-Charles+De+Gaulle+(CDG),+Roissy-en-France,+Frankreich/llacan+villejuif+adresse/@48.9024495,2.3070045,11z/data=!3m1!4b1!4m14!4m13!1m5!1m1!1s0x47e63e038e4ccf5b:0x42be0982f5ba62c!2m2!1d2.5479245!2d49.0096906!1m5!1m1!1s0x47e671608cba6615:0x952302ded2a0d0ba!2m2!1d2.358777!2d48.796767!3e3>
>
> 7 Rue Guy Môquet
> <https://www.google.com/maps/place/7+Rue+Guy+M%C3%B4quet,+94800+Villejuif,+France/@48.796569,2.359287,14z/data=!4m5!3m4!1s0x47e6716092bb7f5f:0xa8e75023b9ba16b!8m2!3d48.7967672!4d2.3587773?hl=fr>
>
> 7 Rue Guy Môquet
>
> 7 Rue Guy Môquet, 94800 Villejuif, France
>
> <https://www.google.com/maps/place/7+Rue+Guy+M%C3%B4quet,+94800+Villejuif,+France/@48.796569,2.359287,14z/data=!4m5!3m4!1s0x47e6716092bb7f5f:0xa8e75023b9ba16b!8m2!3d48.7967672!4d2.3587773?hl=fr>
>
> Once you're at the gate, ring the bell, tell the guard your name and that
> you're a visitor and your name's on their list. I can't recall right now
> what the building is called - each building is labelled with a letter.
> Anyway, just ask the guard! Or call Katya or me to pick you up at the gate.
> In fact, you can't really get into the buildiung unless you have a
> card...except via the metal staircase through the kitchen door ´, which is
> usually propped open.
>
> Just in case you have any problem getting there, or in case they don't let
> you in - which has happened before but I don't think it will - you can
> contact Katya - this is her number: 0033-766119605 - or me:
> 0049-15163221386.
> Have a good trip!
>
> Rebecca
>
>
>
>
>
>
> Am Montag, 28. Oktober 2019, 12:53:48 MEZ hat Тимофей Архангельский <
> timarkh@gmail.com> Folgendes geschrieben:
>
>
> Hi Rebecca and Abbie,
>
> Thanks! My name should actually be transliterated as "Timofey
> Arkhangelskiy" (at least that's what I normally use). My number
> is +491747125521, and the dates are correct.
>
> Best,
> Timofey
>
> пт, 25 окт. 2019 г. в 17:32, rebecca voll <rebecca_voll@yahoo.de>:
>
> Thanks Abbie!
>
> Hi Timofey!
>
> I'm also part of the Discourse reporting project...
> Could you please send me your telephone number?
> I need it to issue an application for access on campus for you on the
> 5th-6th of november. Let me know if you want to stay longer, then I will
> apply for more days.
> The system requires that we apply before a visitor comes, otherwise they
> are not able to get onto campus, so it is important that we cover the whole
> time you will actually be at the Llacan.
> Thanks for sending me your number and the exact dates!
> Best wishes,
>
> Rebecca
>
>
> Am Freitag, 25. Oktober 2019, 16:30:48 MESZ hat Abbie Hantgan <
> ahantgan@gmail.com> Folgendes geschrieben:
>
>
> Hi Rebecca,
>
> This is to introduce you to Timofey with his contact details so you can
> make sure he has access to campus from November 5-6.
>
> Hi Timofey,
>
> Please make sure that I transliterated your name correctly:
>
> Тимофей Архангельский (Timofey Arhangelski)
> timarkh@gmail.com
>
> Looking forward to seeing you soon,
>
> Abbie
>
>

**Comment by rvoll** [comment]
Hi Timofey!
Yes. Sorry! Somehow it is an issue...Anyway, it's fine if you just call when you're there or as the guard to direct you to the Llacan building.Our actual meeting is gonna take place at 2pm in the adjacent building: on the ground floor in building D - where also the library is.See you tomorrow!Have a good trip!

Rebecca


    Am Montag, 4. November 2019, 15:31:46 MEZ hat Тимофей Архангельский <timarkh@gmail.com> Folgendes geschrieben:  
 
 Okay, thanks a lot! Sounds reasonably complicated, let's see if I manage to get in. :) What about the time: can I just show up at any moment, or should I warn you some time in advance, e.g. when I get on the Paris-bound train?
пт, 1 нояб. 2019 г. в 23:39, rebecca voll <rebecca_voll@yahoo.de>:

 Hi Timofey!
Thanks for the details.
This is just to make sure you reach campus and get inside:
This is where the Villejuif cnrs campus is:
Paris-Charles-de-Gaulle-flygplatsen to Cnrs Délégation Paris-Villejuif

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Paris-Charles-de-Gaulle-flygplatsen to Cnrs Délégation Paris-Villejuif

Hitta lokala företag, titta på kartor och hämta vägbeskrivningar i Google Maps.
 |

 |

 |


7 Rue Guy Môquet

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
7 Rue Guy Môquet

7 Rue Guy Môquet, 94800 Villejuif, France
 |

 |

 |


Once you're at the gate, ring the bell, tell the guard your name and that you're a visitor and your name's on their list. I can't recall right now what the building is called - each building is labelled with a letter. Anyway, just ask the guard! Or call Katya or me to pick you up at the gate. In fact, you can't really get into the buildiung unless you have a card...except via the metal staircase through the kitchen door ´, which is usually propped open.

Just in case you have any problem getting there, or in case they don't let you in - which has happened before but I don't think it will - you can contact Katya - this is her number: 0033-766119605 - or me: 0049-15163221386.Have a good trip!
Rebecca






    Am Montag, 28. Oktober 2019, 12:53:48 MEZ hat Тимофей Архангельский <timarkh@gmail.com> Folgendes geschrieben:  
 
 Hi Rebecca and Abbie,
Thanks! My name should actually be transliterated as "Timofey Arkhangelskiy" (at least that's what I normally use). My number is +491747125521, and the dates are correct.
Best,Timofey
пт, 25 окт. 2019 г. в 17:32, rebecca voll <rebecca_voll@yahoo.de>:

 Thanks Abbie!
Hi Timofey!
I'm also part of the Discourse reporting project...Could you please send me your telephone number?
I need it to issue an application for access on campus for you on the 5th-6th of november. Let me know if you want to stay longer, then I will apply for more days.The system requires that we apply before a visitor comes, otherwise they are not able to get onto campus, so it is important that we cover the whole time you will actually be at the Llacan.
Thanks for sending me your number and the exact dates!
Best wishes,
Rebecca


    Am Freitag, 25. Oktober 2019, 16:30:48 MESZ hat Abbie Hantgan <ahantgan@gmail.com> Folgendes geschrieben:  
 
 Hi Rebecca,
This is to introduce you to Timofey with his contact details so you can make sure he has access to campus from November 5-6. 

Hi Timofey,
Please make sure that I transliterated your name correctly:

Тимофей Архангельский (Timofey Arhangelski)timarkh@gmail.com
Looking forward to seeing you soon,

Abbie

**Comment by rvoll** [comment]
Hey guys! 

So far only Abbie signed up for the ELAN QnA session...Is anyone interested?This time I don't have enough questions to fill up the whole time.It's a great occasion to solve or discuss your ELAN problems! And in case you don't have any yet, it is a good motivatin to start transcribing and have your questions answered as they come up!If you are interested, enter the times you are available to skype on when2meet!
ELAN QnA session 2 - When2meet

| 
| 
|  | 
ELAN QnA session 2 - When2meet


 |

 |

 |



If skype desn't work for you - maybe you can suggest a better alternative!
Rebecca
