### ISSUE TITLE
News about ElanCorpA

### ISSUE THREAD

**Issue by KatyaAplonova** [KatyaAplonova/ReportedDiscourseProject#39]
This week we spent a loooot of time with Christian and I feel that I need to write up major points (they are only two, but still), because I'm afraid to forget everything 🙈

__1. Universal POS__
Christian almost finished a script which allows us to create new tier in multiple elan files and replace values from source tier with correspondency tables. It has a nice application interface, where you can choose a source tier, a copy tier and a directory where are files to treat. And there is a window, where you copy paste correspondency table with pos to change.

Using this, we will create universal pos tier in all our files. Moreover, those, who have morpheme level pos, could create a tier for world level pos, where only the principle pos will appear.

__2. Parse function__
Elan CorpA has a function Parse, which nobody is actually using. It saves all mb level annotations and you can reuse them to parse unannotated files, which saves a lot of time and works like an error mining, because you can see, whether you have different variants of parsing of the same word form. 

So, those who have a lot of annotated files could enjoy auto-tagging of new files...  Tell me, if want to know more about Parse. Now, I'm trying to make it work with my Bashkir data.

**Comment by TanyaNikitina** [comment]
Yes, I want to use the Parse, but it does not run on my machine (there must be a bug or something).

**Comment by IndianaTones** [comment]
The script is now complete!  Hope Xstian will have an opportunity to show us its power next week.

**Comment by rvoll** [comment]
Hey Katya! Excuse the delayed reply - I would love to learn more about parse! Sounds like this could save some time... I find the interlinearization process with ELAN somewhat tedious and think it should flow better. So maybe parse could do the job...
Maybe you can give us a brief intro next week? Or - if the time is too short, we could do it during the skype session for the ELAN QnA session! What do you think?
