### ISSUE TITLE
project meeting 2019-10-24, 10:30 a.m.

### ISSUE THREAD

**Issue by rvoll** [KatyaAplonova/ReportedDiscourseProject#40]
AGENDA

- discuss close-to-final panel submission
- discuss suggestions for intriguing corpus queries
- present potential contributions for the Grammar of thinking (SLE 2020)
- How to make pdfs of the articles listed in Zotero available to all project members (Becky)
- update from everyone about their expriences with groups and links (can be continued on Friday)

- discuss ELAN annotation issues > Friday 1pm

**Comment by IndianaTones** [comment]
welcome @Lacina-Silue !
