### ISSUE TITLE
Summary of upcoming SLE 53 deadlines

### ISSUE THREAD

**Issue by Avamuru** [KatyaAplonova/ReportedDiscourseProject#45]
**Nov 8** - 300 word abstract - **TYPOLOGICAL APPROACHES TO DISCOURSE PHENOMENA** (see new item in [venues](https://github.com/KatyaAplonova/ReportedDiscourseProject/projects/1) card or read call [here](http://www.sle2020.eu/downloads/workshops/Typological%20approaches%20to%20discourse%20phenomena.pdf). I think someone from our project could present on the _methodological proposals on how  to  collect,  examine  and  compare cross-linguistic  data  on  discourse  phenomena_ mentioned in the call.

**Nov 10** - 300 word abstract  - **The grammar of thinking** (Spronk)

**Nov 20** - Workshop organizers have a **Nov 20** deadline to submit to SLE, but individual papers are subject to the dates above. 

**Jan 15, 2020** - Non-workshop connected abstracts are can also be submitted for SLE general sessions. If a paper is accepted for a workshop, it must also be submitted as a full abstract of 500 words to the general call for papers - due **Jan 15, 2020**.

**Comment by rvoll** [comment]
Hey Becky!
Thanks!!!
This is very helpful!
