### ISSUE TITLE
Nov 28 - Guillaume

### ISSUE THREAD

**Issue by TanyaNikitina** [KatyaAplonova/ReportedDiscourseProject#46]
Can anyone be around on November 28 to meet Guillaume Guitang who would like to pass by on that day? He will need to hand in his equipment and get updated on what we have been doing.

**Comment by IndianaTones** [comment]
Perhaps @LacinaSilue? I think otherwise @KatyaAplonova will be at LIFT and I will be away.

**Comment by LacinaSilue** [comment]
Yes, I will be around on 28, but in the afternoon. At what time does he want to pass by?

**Comment by TanyaNikitina** [comment]
Perfect thanks! I will get you in touch and you can decide what time works best.

**Comment by rvoll** [comment]
Maybe I could be there, too but not sure yet.
