### ISSUE TITLE
tomorrow's session

### ISSUE THREAD

**Issue by TanyaNikitina** [KatyaAplonova/ReportedDiscourseProject#47]
Hi all,
It seems that there will be another big meeting in the salle de reunions tomorrow at 14h. If we can get a projector we could perhaps use the hall room in our new extended office? Can we project on the wall there?
T

**Comment by IndianaTones** [comment]
Hi Tanya,

Are you referring to the new office space where Bernard works? If so, there are no complete walls in the main room there for projecting. Perhaps we could somehow work around the screen on my desk?

**Comment by TanyaNikitina** [comment]
I was thinking of the room/hall one passes on the way to Bernard's office, the one with an oval table (from which one could also enter Becky's office). I think Jeanne meant one of the walls to be suitable for projecting but perhaps it is not ready yet?

**Comment by IndianaTones** [comment]
Yes, there are cabinets in the way of the one full wall space.

**Comment by IndianaTones** [comment]
Hi all - 

**Update**

The Conference Room in Building D (where the Reported Discourse Workshop took place) will be available for us to meet from 14:00 onwards.

**Comment by rvoll** [comment]
Perfect! So should we meet there at 2pm or maybe a bit earlier to make sure everything works?
