### ISSUE TITLE
problems with the template?

### ISSUE THREAD

**Issue by TanyaNikitina** [KatyaAplonova/ReportedDiscourseProject#50]
It looks like the template files uploaded here are again not the correct ones! At least the controlled vocabulary for the qt level does not look correct. Let us please upload the correct version of the templates and make sure we all use it! I will send by email the latest versions that I have .

**Comment by IndianaTones** [comment]
I uploaded the one that you sent Tanya, but will make the multiple participant one as well. 

For those of you who have been using a template that differs from that which Tanya has, don't worry nor try to fix the issues. @KatyaAplonova and I are hoping to soon welcome an intern who will address all these inconsistencies.

**Comment by IndianaTones** [comment]
Corrected templates are now uploaded. Please use these if you are starting to annotate a new file, if not, don't worry, they will be fixed later.
