### ISSUE TITLE
Acknowledgments and funding info

### ISSUE THREAD

**Issue by IndianaTones** [KatyaAplonova/ReportedDiscourseProject#54]
@TanyaNikitina provided me with this very helpful phrases and I keep losing track of it so I will just make this issue for now and then put it somewhere more permanently so that we can all copy and paste it as needed:

> "This project has received funding from the European Research Council (ERC) under the European Union’s Horizon 2020 research and innovation programme (grant agreement No 758232)."

**Comment by rvoll** [comment]
I added it to the Wiki. I think that is the best place!
