### ISSUE TITLE
Tomorrow we start at 10!

### ISSUE THREAD

**Issue by KatyaAplonova** [KatyaAplonova/ReportedDiscourseProject#57]
Topics to discuss are:
- Abbie's weird pronouns
- Katya's new construction of reported discourse
- Lacina's data?
- participation in hackathon in Orleans 
- ... ?

**Comment by IndianaTones** [comment]
Hi all - just to say that I uploaded yesterday's presentation and dataset into a new folder: https://github.com/KatyaAplonova/ReportedDiscourseProject/tree/master/meetings/AHS-Dogon
